/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const AirtableAPIOptions = t.iface([], {
  "apiKey": "string",
});

export const AirtableSchema = t.iface([], {
  "tables": t.array("AirtableSchemaTable"),
});

export const AirtableSchemaTable = t.iface([], {
  "id": "string",
  "name": "string",
  "fields": t.array("AirtableSchemaField"),
});

export const AirtableSchemaField = t.iface([], {
  "id": "string",
  "name": "string",
  "type": "string",
  "options": t.opt("any"),
});

const exportedTypeSuite: t.ITypeSuite = {
  AirtableAPIOptions,
  AirtableSchema,
  AirtableSchemaTable,
  AirtableSchemaField,
};
export default exportedTypeSuite;
