/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const AirtableAPIOptions = t.iface([], {
  "apiKey": "string",
});

export const AirtableBaseSchema = t.iface([], {
  "tables": t.array("AirtableTableSchema"),
});

export const AirtableTableSchema = t.iface([], {
  "id": "string",
  "name": "string",
  "fields": t.array("AirtableFieldSchema"),
});

export const AirtableFieldSchema = t.iface([], {
  "id": "string",
  "name": "string",
  "type": "string",
  "options": t.opt("any"),
});

const exportedTypeSuite: t.ITypeSuite = {
  AirtableAPIOptions,
  AirtableBaseSchema,
  AirtableTableSchema,
  AirtableFieldSchema,
};
export default exportedTypeSuite;
