/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Config = t.iface([], {
  "id": "string",
  "key": "ConfigKey",
  "value": "ConfigValue",
  "createdAt": "string",
  "updatedAt": "string",
  "org": t.opt("ConfigOrg"),
});

export const ConfigOrg = t.iface([], {
  "id": "number",
  "name": "string",
  "domain": t.union("string", "null"),
});

export const ConfigKey = t.union(t.lit("audit_log_streaming_destinations"), t.lit("latest_version_available"));

export const ConfigValue = t.union("AuditLogStreamingDestinations", "LatestVersionAvailable");

export const AuditLogStreamingDestinations = t.array("AuditLogStreamingDestination");

export const AuditLogStreamingDestination = t.iface([], {
  "id": "string",
  "name": "AuditLogStreamingDestinationName",
  "url": "string",
  "token": t.opt("string"),
});

export const AuditLogStreamingDestinationName = t.union(t.lit("splunk"), t.lit("other"));

export const LatestVersionAvailable = t.iface([], {
  "version": "string",
  "isNewer": "boolean",
});

const exportedTypeSuite: t.ITypeSuite = {
  Config,
  ConfigOrg,
  ConfigKey,
  ConfigValue,
  AuditLogStreamingDestinations,
  AuditLogStreamingDestination,
  AuditLogStreamingDestinationName,
  LatestVersionAvailable,
};
export default exportedTypeSuite;
