/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ExistingDocSchema = t.iface([], {
  "tables": t.array("ExistingTableSchema"),
});

export const ExistingTableSchema = t.iface([], {
  "id": "string",
  "ref": "number",
  "columns": t.array("ExistingColumnSchema"),
});

export const ExistingColumnSchema = t.iface([], {
  "id": "string",
  "ref": "number",
  "label": t.opt("string"),
});

export const DocSchemaSqlResult = t.array(t.iface([], {
  "tableRef": "number",
  "tableId": "string",
  "colRef": "number",
  "colId": "string",
  "colLabel": "string",
}));

const exportedTypeSuite: t.ITypeSuite = {
  ExistingDocSchema,
  ExistingTableSchema,
  ExistingColumnSchema,
  DocSchemaSqlResult,
};
export default exportedTypeSuite;
