/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ExistingDocSchema = t.iface([], {
  "tables": t.array("ExistingTableSchema"),
});

export const ExistingTableSchema = t.iface([], {
  "id": "string",
  "name": t.opt("string"),
  "ref": t.opt("number"),
  "columns": t.array("ExistingColumnSchema"),
});

export const ExistingColumnSchema = t.iface([], {
  "id": "string",
  "ref": "number",
  "label": t.opt("string"),
  "isFormula": "boolean",
});

const exportedTypeSuite: t.ITypeSuite = {
  ExistingDocSchema,
  ExistingTableSchema,
  ExistingColumnSchema,
};
export default exportedTypeSuite;
