/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const SharedChoiceList = t.iface([], {
  "name": "string",
  "choices": t.array("string"),
  "choiceColors": t.opt(t.iface([], {
    [t.indexKey]: "string",
  })),
});

export const DocumentSettings = t.iface([], {
  "locale": "string",
  "currency": t.opt("string"),
  "engine": t.opt("EngineCode"),
  "attachmentStoreId": t.opt("string"),
  "baseAction": t.opt("DocState"),
  "sharedChoiceLists": t.opt(t.iface([], {
    [t.indexKey]: "SharedChoiceList",
  })),
});

export const EngineCode = t.lit("python3");

export const DocState = t.iface([], {
  "n": "number",
  "h": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  SharedChoiceList,
  DocumentSettings,
  EngineCode,
  DocState,
};
export default exportedTypeSuite;
