/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const DocumentSettings = t.iface([], {
  "locale": "string",
  "currency": t.opt("string"),
  "engine": t.opt("EngineCode"),
  "attachmentStoreId": t.opt("string"),
});

export const EngineCode = t.lit('python3');

const exportedTypeSuite: t.ITypeSuite = {
  DocumentSettings,
  EngineCode,
};
export default exportedTypeSuite;
