/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const GristBuild = t.union(t.lit("full"), t.lit("community"));

export const HelpUsImproveDeploymentType = t.union(t.lit("saas"), t.lit("core"), t.lit("enterprise"), t.lit("electron"), t.lit("static"));

export const HelpUsImproveSubmission = t.iface([], {
  "installationId": "string",
  "loginWithGristClientId": "string",
  "referralSource": "string",
  "role": "string",
  "subscribeToUpdates": "boolean",
  "email": "string",
  "deploymentType": t.opt("HelpUsImproveDeploymentType"),
  "build": "GristBuild",
});

export const HelpUsImproveResponse = t.iface([], {
  "persistFailed": "boolean",
  "subscribeFailed": "boolean",
  "persistUnrecoverable": t.opt("boolean"),
});

const exportedTypeSuite: t.ITypeSuite = {
  GristBuild,
  HelpUsImproveDeploymentType,
  HelpUsImproveSubmission,
  HelpUsImproveResponse,
};
export default exportedTypeSuite;
