/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ServiceAccountAllOptional = t.iface([], {
  "label": t.union("string", "undefined"),
  "description": t.union("string", "undefined"),
  "endOfLife": t.union("string", "undefined"),
});

export const PatchServiceAccount = t.name("ServiceAccountAllOptional");

export const PostServiceAccount = t.iface(["ServiceAccountAllOptional"], {
  "endOfLife": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  ServiceAccountAllOptional,
  PatchServiceAccount,
  PostServiceAccount,
};
export default exportedTypeSuite;
