/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ServiceAccountAllOptional = t.iface([], {
  "label": t.union("string", "undefined"),
  "description": t.union("string", "undefined"),
  "expiresAt": t.union("string", "undefined"),
});

export const ServiceAccountApiResponse = t.iface([], {
  "login": t.union("string", "undefined"),
  "key": t.union("string", "null"),
  "label": "string",
  "description": "string",
  "expiresAt": "string",
  "hasValidKey": "boolean",
});

export const ServiceAccountCreationResponse = t.iface(["ServiceAccountApiResponse"], {
  "login": "string",
  "key": "string",
});

export const PatchServiceAccount = t.name("ServiceAccountAllOptional");

export const PostServiceAccount = t.iface(["ServiceAccountAllOptional"], {
  "expiresAt": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  ServiceAccountAllOptional,
  ServiceAccountApiResponse,
  ServiceAccountCreationResponse,
  PatchServiceAccount,
  PostServiceAccount,
};
export default exportedTypeSuite;
