/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const PostServiceAccount = t.iface([], {
  "label": t.union("string", "undefined"),
  "description": t.union("string", "undefined"),
  "endOfLife": t.union("string", "undefined"),
});

export const PatchServiceAccount = t.name("PostServiceAccount");

const exportedTypeSuite: t.ITypeSuite = {
  PostServiceAccount,
  PatchServiceAccount,
};
export default exportedTypeSuite;
