/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const WebhookFields = t.iface([], {
  "url": "string",
  "eventTypes": t.array(t.union(t.lit("add"), t.lit("update"))),
  "tableId": "string",
  "enabled": t.opt("boolean"),
  "isReadyColumn": t.opt(t.union("string", "null")),
});

export const WebhookSubscribe = t.iface([], {
  "url": "string",
  "eventTypes": t.array(t.union(t.lit("add"), t.lit("update"))),
  "enabled": t.opt("boolean"),
  "isReadyColumn": t.opt(t.union("string", "null")),
});

export const WebhookUpdate = t.iface([], {
  "id": "string",
  "fields": "WebhookPatch",
});

export const WebhookPatch = t.iface([], {
  "url": t.opt("string"),
  "eventTypes": t.opt(t.array(t.union(t.lit("add"), t.lit("update")))),
  "tableId": t.opt("string"),
  "enabled": t.opt("boolean"),
  "isReadyColumn": t.opt(t.union("string", "null")),
});

const exportedTypeSuite: t.ITypeSuite = {
  WebhookFields,
  WebhookSubscribe,
  WebhookUpdate,
  WebhookPatch,
};
export default exportedTypeSuite;
