blank_issues_enabled: false
contact_links:
  - name: 🤷💻🤦 Question/Forum
    url: https://community.getgrist.com/
    about: You can ask and answer other questions here
  - name: 💬 Discord
    url: https://discord.com/invite/MYKpYQ3fbP
    about: Chat with us via Discord for quick Q/A here and sharing tips
