/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const AirtableAPIOptions = t.iface([], {
  "apiKey": "string",
});

export const AirtableListBasesResponse = t.iface([], {
  "bases": t.array(t.iface([], {
    "id": "string",
    "name": "string",
    "permissionLevel": t.array(t.union(t.lit("none"), t.lit("read"), t.lit("comment"), t.lit("edit"), t.lit("create"))),
  })),
  "offset": t.opt("string"),
});

export const AirtableBaseSchema = t.iface([], {
  "tables": t.array("AirtableTableSchema"),
});

export const AirtableTableSchema = t.iface([], {
  "id": "string",
  "name": "string",
  "primaryFieldId": "string",
  "fields": t.array("AirtableFieldSchema"),
});

export const AirtableFieldSchema = t.iface([], {
  "id": "string",
  "name": "string",
  "type": "string",
  "options": t.opt(t.iface([], {
    [t.indexKey]: "any",
  })),
});

export const AirtableChoiceValue = t.iface([], {
  "id": "string",
  "name": "string",
  "color": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  AirtableAPIOptions,
  AirtableListBasesResponse,
  AirtableBaseSchema,
  AirtableTableSchema,
  AirtableFieldSchema,
  AirtableChoiceValue,
};
export default exportedTypeSuite;
