/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Edition = t.union(t.lit("core"), t.lit("enterprise"));

export const IGristCoreConfigFileContents = t.iface([], {
  "edition": t.opt("Edition"),
});

export const IGristCoreConfig = t.iface([], {
  "edition": "any",
});

const exportedTypeSuite: t.ITypeSuite = {
  Edition,
  IGristCoreConfigFileContents,
  IGristCoreConfig,
};
export default exportedTypeSuite;
