/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IGristCoreConfigFileLatest = t.name("IGristCoreConfigFileV1");

export const IGristCoreConfigFileV1 = t.iface([], {
  "version": t.lit("1"),
  "edition": t.opt(t.union(t.lit("core"), t.lit("enterprise"))),
});

export const IGristCoreConfigFileV0 = t.iface([], {
  "version": "undefined",
});

const exportedTypeSuite: t.ITypeSuite = {
  IGristCoreConfigFileLatest,
  IGristCoreConfigFileV1,
  IGristCoreConfigFileV0,
};
export default exportedTypeSuite;
