/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const NewRecord = t.iface([], {
  "fields": t.opt(t.iface([], {
    [t.indexKey]: "CellValue",
  })),
});

export const Record = t.iface([], {
  "id": "number",
  "fields": t.iface([], {
    [t.indexKey]: "CellValue",
  }),
});

export const RecordsPatch = t.iface([], {
  "records": t.tuple("Record", t.rest(t.array("Record"))),
});

export const RecordsPost = t.iface([], {
  "records": t.tuple("NewRecord", t.rest(t.array("NewRecord"))),
});

const exportedTypeSuite: t.ITypeSuite = {
  NewRecord,
  Record,
  RecordsPatch,
  RecordsPost,
};
export default exportedTypeSuite;
