FROM registry.access.redhat.com/ubi9 AS ubi-micro-build
RUN mkdir -p /mnt/rootfs
RUN dnf install --installroot /mnt/rootfs curl --releasever 9 --setopt install_weak_deps=false --nodocs -y && \
    dnf --installroot /mnt/rootfs clean all && \
    rpm --root /mnt/rootfs -e --nodeps setup

FROM ghcr.io/jqlang/jq:1.7 AS jqsrc
FROM quay.io/keycloak/keycloak:26.3 AS builder

COPY --from=ubi-micro-build /mnt/rootfs /
COPY --from=jqsrc --chmod=0755 /jq /usr/local/bin/jq

ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

WORKDIR /opt/keycloak
RUN /opt/keycloak/bin/kc.sh build --features=scripts
