services:
  grist:
    image: gristlabs/grist:latest
    volumes:
      # Where to store persistent data, such as documents.
      - ${GRIST_DATA_DIR:-./grist_local_data}:/persist
    ports:
      - 8484:8484
