apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grist.fullname" . }}-secrets
  labels:
    {{- include "grist.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.GRIST_SESSION_SECRET }}
  {{- if lt (len .Values.config.GRIST_SESSION_SECRET) 32 }}
  {{- fail "GRIST_SESSION_SECRET must be at least 32 characters long" }}
  {{- end }}
  GRIST_SESSION_SECRET: {{ .Values.config.GRIST_SESSION_SECRET | b64enc }}
  {{- else }}
  GRIST_SESSION_SECRET: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- if .Values.config.extraEnv.GRIST_SMTP_PASSWORD }}
  GRIST_SMTP_PASSWORD: {{ .Values.config.extraEnv.GRIST_SMTP_PASSWORD | b64enc }}
  {{- end }}
  TYPEORM_PASSWORD: {{ include "grist.database.password" . | b64enc }}
  GRIST_DOCS_MINIO_ACCESS_KEY: {{ include "grist.minio.accessKey" . | b64enc }}
  GRIST_DOCS_MINIO_SECRET_KEY: {{ include "grist.minio.secretKey" . | b64enc }}
