name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'Charts/grist/**'
    tags:
      - 'grist-*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Add dependency repositories
        run: |
          EXPECTED_FINGERPRINT="3ac88d84e4b7c729262796c6d5c7d11d5a6a6b1a3c262c4af8b2bbf5a08d451a"
          ACTUAL_FINGERPRINT=$(curl -s https://charts.bitnami.com/bitnami/index.yaml | sha256sum | cut -d' ' -f1)
          if [ "$EXPECTED_FINGERPRINT" != "$ACTUAL_FINGERPRINT" ]; then
            echo "Repository fingerprint verification failed"
            exit 1
          fi
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: Charts
